require('config.globals')
require('config.options')
require('config.keymap')
require('config.autocmd')
require('config.lsp')

require('plugins.vague')
require('plugins.oil')
require('plugins.mini')
require('plugins.fzf')
require('plugins.gitsigns')
require('plugins.indent-blankline')
require('plugins.neogit')
require('plugins.outline')
